/*
-- TODO: ddl-auto 옵션 줬는데 왜 already exists 뜨는지 확인해볼것
-- 상품 테이블
CREATE TABLE GOODS_DTL (
    GOODS_ID BIGINT
    , GOODS_NM VARCHAR(255)
    , SALE_PRICE INTEGER
    , DISCOUNT_PRICE INTEGER
    , STOCK_QTY INTEGER
    , PRIMARY KEY (GOODS_ID)
);

-- 주문 기본 테이블
CREATE TABLE ORDER_BAS (
    ORDER_NUM BIGINT NOT NULL AUTO_INCREMENT
    , CUST_NUM BIGINT
    , ORDER_DTTM DATETIME
    , PRIMARY KEY (ORDER_NUM)
);

-- 주문 상세 테이블
CREATE TABLE ORDER_DTL (
    ORDER_NUM BIGINT
    , ORDER_SEQ INTEGER
    , GOODS_ID BIGINT
    , GOODS_NM VARCHAR(255)
    , ORDER_STATUS VARCHAR(5)
    , GOODS_PRICE INTEGER
    , ORDER_DTTM DATETIME
    , PRIMARY KEY (ORDER_NUM)
);

-- 고객 정보 테이블
CREATE TABLE CUST_INFO (
    CUST_NUM BIGINT NOT NULL AUTO_INCREMENT
    , CUST_NM VARCHAR(10)
    , PRIMARY KEY (CUST_NUM)
);
*/
